weights: ./pretrained/yolo5l.pt
cfg: ./models/yolov5l.yaml
data: ./data/FLDrone.yaml
hyp: ./data/hyps/hyp.VisDrone.yaml
epochs: 80
batch_size: 4
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 8
project: ./runs/train/FL
name: image_size_1280_temporal_YOLO5L_5_frames_FL_end_to_end
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/FL/image_size_1280_temporal_YOLO5L_5_frames_FL_end_to_end
